### ISSUE TITLE
File move help

### ISSUE THREAD

**Issue by michael-cannon** [michael-cannon/cuddly-giggle#1]
Good afternoon @saurabhsirdixit,

Could you please move 
      cuddly-giggle/.gitignore/zoom-google-cal-bookmarklet.js    
to
      cuddly-giggle/zoom-google-cal-bookmarklet.js
?

I did something stupid and didn't realize it till today.

Thank you,

Michael

**Comment by saurabhsirdixit** [comment]
@michael-cannon done, please check : https://github.com/michael-cannon/cuddly-giggle
Note: I also deleted .gitignore folder and moved both the files to root.

**Comment by michael-cannon** [comment]
Great work @saurabhsirdixit , looks good.
